import Head from 'next/head'
import Articles from "../components/Articles"
import getArticles from "../src/api-requests"
import styles from '../styles/Home.module.css'

export default function Page({ data }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>MoodVenture</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				{data ? <Articles articles={data} /> : <>No Articles found.</>}
			</main>
		</div>
	)
}

export async function getServerSideProps() {
	// Fetch data from external API
	try {
		const data = await getArticles()

		// Pass data to the page via props
		return { props: { data } }
	} catch (e) {
		console.error(e)
	}
}
