import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useUser } from '@auth0/nextjs-auth0';

export default function Home() {
  const { user, error, isLoading } = useUser();
  console.log(user)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='text-center'>
        <button className='text-white bg-cyan-400 py-2 px-3'><a href="/api/auth/login">Login</a></button>
        <button className='text-white bg-cyan-400 py-2 px-3'><a href="/api/auth/logout">Logout</a></button>
      </div>
    </div>
  )
}
